### ISSUE TITLE
Opacidade das cores

### ISSUE THREAD

**Issue by pedroramon** [fgcintra/fatec-franca-2016-1#5]
Nas instruções do trabalho, foi solicitado que troquemos as cores de rgb para rgba, porém foi solicitado que a opacidade fique em 0%, o que deixa a cor transparente. Me parece um equivoco, confirma?

**Comment by faustocintra** [comment]
Confirmo, eu deveria ter escrito transparência 0%.

fausto@fgcintra.pro.br | http://fgcintra.pro.br
Currículo Lattes: http://lattes.cnpq.br/5529456425773756

Faculdade de Tecnologia de Franca "Dr. Thomaz Novelino" - Fatec Franca

_Atendimento a alunos - 1º semestre de 2016_
Segundas-feiras: das 10h às 11h40
Terças-feiras: das 13h às 14h40
Quintas-feiras: das 20h50 às 22h30

2016-06-07 18:41 GMT-03:00 Pedro Ramon notifications@github.com:
